[project]
name = "pdf-mcp-server"
version = "0.1.0"
description = "MCP server for reading PDF files using pdfplumber"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pdfplumber>=0.11.7",
    "mcp>=1.1.0",
]

[project.scripts]
pdf-mcp-server = "main:main"
